---
title: "Sims"
output: html_document
date: '2022-09-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
 
 ATE <- 1
library(data.table)
outs <- fread("SimsHALCATE2.csv")
 
 # outs$const[outs$const == 3] <- "overlap: 1e-06"
# outs$const[outs$const == 5] <- "overlap: 1e-10"
# outs$const[outs$const == 8] <- "overlap: 1e-15"
outs$const[outs$const == 1] <- "overlap: 0.025"

outs$const[outs$const == 4] <- "overlap: 1e-06"
outs$const[outs$const == 7] <- "overlap: 1e-09"
 
 

out_sieveIF <- outs[,c("const", "n", "iter", "estimate", "CI_left", "CI_right", "name")]
out_sieveIF$method = "sieve_IF"
col_names <- colnames(out_sieveIF)

 out_sieveIF_df <- outs[,c("const", "n", "iter", "estimate", "CI_df_left", "CI_df_right", "name")]
out_sieveIF_df$method = "sieve_IF_df_adjusted"
colnames(out_sieveIF_df) <- col_names

out_sieveboot <- outs[,c("const", "n", "iter", "estimate", "CI_boot_left", "CI_boot_right", "name")]
out_sieveboot$method = "sieve_boot"
colnames(out_sieveboot) <- col_names

out_tmle <- outs[,c("const", "n", "iter", "estimate_npglm", "CI_left_npglm", "CI_right_npglm", "name")]
out_tmle$method = "npglm"
colnames(out_tmle) <- col_names

out_tmlesp <- outs[,c("const", "n", "iter", "estimate_spglm", "CI_left_spglm", "CI_right_spglm", "name")]
out_tmlesp$method = "spglm"
colnames(out_tmlesp) <- col_names

 
results <- rbind(out_sieveIF, out_sieveIF_df,  out_tmle, out_tmlesp)
results[-grep( "W",results$name ), "name"] <- "intercept"
results[grep( "W",results$name ), "name"] <- "X"

coverage <- results[, mean(ATE >= CI_left & ATE <= CI_right), by = c("const", "method", "n", "name")]
CI_width <- results[, mean(CI_right - CI_left), by = c("const", "method", "n", "name")]
cov_oracle = results[, mean(abs(estimate-ATE) <=  1.959964 * sd(estimate))  ,  by = c("const", "n", "method", "name")]
bias <- results[, mean(estimate - ATE), by = c("const", "method", "n", "name")]
se <- results[, sd(estimate - ATE), by = c("const", "method", "n", "name")]

plot_data <- data.table(name = coverage$name, const = coverage$const, method = coverage$method, n = coverage$n,  cov_oracle=cov_oracle[[5]],
           bias = abs(bias[[5]]),
           se = se[[5]],
           coverage = coverage[[5]],
           CI_width = CI_width[[5]]
           )

library(ggplot2)
plot_data_orig <- plot_data
```
 
 
```{r}

plot_data <- plot_data_orig
 
plot_data <- plot_data[plot_data$name %in% c("intercept")]
ggplot(plot_data[method %in% c("npglm", "spglm", "sieve_IF")], aes(x=n, y = bias,   color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical Bias", color = "Method", group = "Method", linetype = "Method")


 
 ggsave("SimPlotHALCATE_biasinter.pdf", width = 7, height = 4)
 

ggplot(plot_data[method %in%  c("npglm", "spglm", "sieve_IF")], aes(x=n, y = se,  color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical Standard Error", color = "Method", group = "Method", linetype = "Method")

 ggsave("SimPlotHALCATE_seinter.pdf", width = 7, height = 4)
 
 
 
ggplot(plot_data[method %in%  c("npglm", "spglm", "sieve_IF")] , aes(x=n, y = cov_oracle, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Oracle CI coverage", color = "Method", group = "Method", linetype = "Method")  

 ggsave("SimPlotHALCATE_coverage_oracleinter.pdf", width = 7, height = 4)
 
 
 
ggplot(plot_data[method %in%  c("npglm", "spglm", "sieve_IF")] , aes(x=n, y = coverage,  color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical CI coverage", color = "Method", group = "Method", linetype = "Method") + scale_y_continuous(breaks = c(0.95, 0.9, 0.8, 0.7, 0.6))

 ggsave("SimPlotHALCATE_coverageinter.pdf", width = 7, height = 4)
 

 
ggplot(plot_data[  method %in% c("npglm", "spglm", "sieve_IF")] , aes(x=n, y = CI_width,  color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5)) + labs(x = "Sample Size (n)", y = "Average CI width", color = "Method", group = "Method", linetype = "Method")

 ggsave("SimPlotHALCATE_CI_widthinter.pdf", width = 7, height = 4)
 
 
```







```{r}

plot_data <- plot_data_orig
 plot_data <- plot_data[plot_data$name %in% c("X")]
ggplot(plot_data[method %in% c("npglm", "spglm", "sieve_IF")], aes(x=n, y = bias,   color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical Bias", color = "Method", group = "Method", linetype = "Method")


 
 ggsave("SimPlotHALCATE_bias_X.pdf", width = 7, height = 4)
 

ggplot(plot_data[method %in%  c("npglm", "spglm", "sieve_IF")], aes(x=n, y = se,  color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical Standard Error", color = "Method", group = "Method", linetype = "Method")

 ggsave("SimPlotHALCATE_se_X.pdf", width = 7, height = 4)
 
 
 
ggplot(plot_data[method %in%  c("npglm", "spglm", "sieve_IF")] , aes(x=n, y = cov_oracle, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Oracle CI coverage", color = "Method", group = "Method", linetype = "Method")  

 ggsave("SimPlotHALCATE_coverage_oracle_X.pdf", width = 7, height = 4)
 
 
 
ggplot(plot_data[method %in%  c("npglm", "spglm", "sieve_IF")] , aes(x=n, y = coverage,  color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical CI coverage", color = "Method", group = "Method", linetype = "Method") + scale_y_continuous(breaks = c(0.95, 0.9, 0.8, 0.7, 0.6))

 ggsave("SimPlotHALCATE_coverage_X.pdf", width = 7, height = 4)
 

 
ggplot(plot_data[  method %in% c("npglm", "spglm", "sieve_IF")] , aes(x=n, y = CI_width,  color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5)) + labs(x = "Sample Size (n)", y = "Average CI width", color = "Method", group = "Method", linetype = "Method")

 ggsave("SimPlotHALCATE_CI_width_X.pdf", width = 7, height = 4)
 
 
```






```{r}
ATE <- 1.811417
#ATE <- 1
library(data.table)
outs <- fread("ComplexParametricHAL3.csv")
outs <- outs[!(const %in% c(5,8))]
#outs <- fread("SimpleParametricHALSmallSamples2.csv")
# outs <- fread("SimpleParametricHAL2.csv")
 # outs <- rbind(fread("LassoHighDim.csv"),fread("LassoHighDim2500.csv"))
outs2 <- fread("ComplexParametricHAL4_85.csv")
outs <- rbind(outs, outs2)

# outs$const[outs$const == 3] <- "overlap: 1e-06"
# outs$const[outs$const == 5] <- "overlap: 1e-10"
# outs$const[outs$const == 8] <- "overlap: 1e-15"

outs$const[outs$const == 3] <- "overlap: 1e-05"
outs$const[outs$const == 5] <- "overlap: 1e-08"
outs$const[outs$const == 8] <- "overlap: 1e-15"

 outs$const[outs$const == 1] <- "overlap: 0.025"

outs$const[outs$const == 4] <- "overlap: 1e-06"
outs$const[outs$const == 7] <- "overlap: 1e-09"
 

out_sieveIF <- outs[,c("const", "n", "iter", "estimate", "CI_left", "CI_right")]
out_sieveIF$method = "sieve_IF"
col_names <- colnames(out_sieveIF)

 out_sieveIF_df <- outs[,c("const", "n", "iter", "estimate", "CI_df_left", "CI_df_right")]
out_sieveIF_df$method = "sieve_IF_df_adjusted"
colnames(out_sieveIF_df) <- col_names

out_sieveboot <- outs[,c("const", "n", "iter", "estimate", "CI_boot_left", "CI_boot_right")]
out_sieveboot$method = "sieve_boot"
colnames(out_sieveboot) <- col_names

out_tmle <- outs[,c("const", "n", "iter", "estimate_tmle", "CI_left_tmle", "CI_right_tmle")]
out_tmle$method = "tmle"
colnames(out_tmle) <- col_names

out_aipw <- outs[,c("const", "n", "iter", "estimate_aipw", "CI_left_aipw", "CI_right_aipw")]
out_aipw$method = "aipw"
colnames(out_aipw) <- col_names

out_lm <- outs[,c("const", "n", "iter", "estimate_lm", "CI_left_lm", "CI_right_lm")]
out_lm$method = "lm"
colnames(out_lm) <- col_names

 

 out_sieve_oracle <-out_sieveIF
 out_sieve_oracle$method <- "sieve_oracle"
 
 out_sieve_oracle[, CI_left:= estimate - qnorm(1-0.05/2) * sd(estimate), by = c("const", "n")]
 out_sieve_oracle[, CI_right:= estimate + qnorm(1-0.05/2) * sd(estimate), by = c("const", "n")]
 
 
 results <- rbind(out_sieve_oracle, out_sieveIF, out_sieveIF_df, out_sieveboot, out_tmle, out_aipw, out_lm)


coverage <- results[, mean(ATE >= CI_left & ATE <= CI_right, na.rm=T), by = c("const", "method", "n")]
CI_width <- results[, mean(CI_right - CI_left, na.rm=T), by = c("const", "method", "n")]
cov_oracle = results[, mean(abs(estimate-ATE) <=  1.959964 * sd(estimate))  ,  by = c("const", "n", "method")]
bias <- results[, mean(estimate - ATE), by = c("const", "method", "n")]
se <- results[, sd(estimate - ATE, na.rm=T), by = c("const", "method", "n")]

plot_data <- data.table(const = coverage$const, method = coverage$method, n = coverage$n,  cov_oracle=cov_oracle[[4]],
           bias = abs(bias[[4]]),
           se = se[[4]],
           coverage = coverage[[4]],
           CI_width = CI_width[[4]]
           )

library(ggplot2)
 
ggplot(plot_data[method %in% c("lm", "aipw", "tmle", "sieve_IF")], aes(x=n, y = bias, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical Bias", color = "Method", group = "Method", linetype = "Method")


 #ggsave("SimPlotLassoHighDim_bias.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_bias.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_bias.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsmallSample_bias.pdf", width = 7, height = 4)

ggplot(plot_data[method %in% c("lm", "aipw", "tmle", "sieve_IF")], aes(x=n, y = se, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical Standard Error", color = "Method", group = "Method", linetype = "Method")


#ggsave("SimPlotHALsmallSample_se.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_se.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_se.pdf", width = 7, height = 4)
# ggsave("SimPlotLassoHighDim_se.pdf", width = 7, height = 4)

 
 
 
ggplot(plot_data[method %in% c("aipw", "tmle","lm", "sieve_IF_df_adjusted")] , aes(x=n, y = cov_oracle, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Oracle CI coverage", color = "Method", group = "Method", linetype = "Method") + scale_y_continuous( )

#ggsave("SimPlotHALsmallSample_coverage_oracle.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_coverage_oracle.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_coverage_oracle.pdf", width = 7, height = 4)
 #ggsave("SimPlotLassoHighDim_coverage_oracle.pdf", width = 7, height = 4)


 plot_data <- plot_data[!(method %in% c("sieve_oracle", "sieve_IF", "sieve_boot"))]
 
 
 
 
 ggplot(plot_data , aes(x=n, y = coverage, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical CI coverage", color = "Method", group = "Method", linetype = "Method") + scale_y_continuous(breaks = c(0.95, 0.93, 0.9, 0.8, 0.7))

#ggsave("SimPlotHALsmallSample_coverage.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_coverage.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_coverage.pdf", width = 7, height = 4)
 #ggsave("SimPlotLassoHighDim_coverage.pdf", width = 7, height = 4)


ggplot(plot_data[!(method %in% c("aipw", "tmle"))] , aes(x=n, y = coverage, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical CI coverage", color = "Method", group = "Method", linetype = "Method")

ggplot(plot_data  , aes(x=n, y = CI_width, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5)) + labs(x = "Sample Size (n)", y = "Average CI width", color = "Method", group = "Method", linetype = "Method")


#ggsave("SimPlotHALsmallSample_CI_width.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_CI_width.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_CI_width.pdf", width = 7, height = 4)
# ggsave("SimPlotLassoHighDim_CI_width.pdf", width = 7, height = 4)


ggplot(plot_data[!(method %in% c("aipw", "tmle"))] , aes(x=n, y = CI_width, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5)) + labs(x = "Sample Size (n)", y = "Average CI width", color = "Method", group = "Method", linetype = "Method")

#ggsave("SimPlot.pdf", width = 8, height = 5)
```






3 smallll





```{r}
ATE <- 1.811417
#ATE <- 1
library(data.table)
outs <- fread("ComplexParametricHAL3.csv")
outs <- outs[!(const %in% c(5,8))]
#outs <- fread("SimpleParametricHALSmallSamples2.csv")
# outs <- fread("SimpleParametricHAL2.csv")
 # outs <- rbind(fread("LassoHighDim.csv"),fread("LassoHighDim2500.csv"))
outs2 <- fread("ComplexParametricHAL4_85.csv")
outs <- rbind(outs, outs2)

# outs$const[outs$const == 3] <- "overlap: 1e-06"
# outs$const[outs$const == 5] <- "overlap: 1e-10"
# outs$const[outs$const == 8] <- "overlap: 1e-15"

outs$const[outs$const == 3] <- "overlap: 1e-05"
outs$const[outs$const == 5] <- "overlap: 1e-08"
outs$const[outs$const == 8] <- "overlap: 1e-15"

 outs$const[outs$const == 1] <- "overlap: 0.025"

outs$const[outs$const == 4] <- "overlap: 1e-06"
outs$const[outs$const == 7] <- "overlap: 1e-09"
 

out_sieveIF <- outs[,c("const", "n", "iter", "estimate", "CI_left", "CI_right")]
out_sieveIF$method = "sieve_IF"
col_names <- colnames(out_sieveIF)

 out_sieveIF_df <- outs[,c("const", "n", "iter", "estimate", "CI_df_left", "CI_df_right")]
out_sieveIF_df$method = "sieve_IF_df_adjusted"
colnames(out_sieveIF_df) <- col_names

out_sieveboot <- outs[,c("const", "n", "iter", "estimate", "CI_boot_left", "CI_boot_right")]
out_sieveboot$method = "sieve_boot"
colnames(out_sieveboot) <- col_names

out_tmle <- outs[,c("const", "n", "iter", "estimate_tmle", "CI_left_tmle", "CI_right_tmle")]
out_tmle$method = "tmle"
colnames(out_tmle) <- col_names

out_aipw <- outs[,c("const", "n", "iter", "estimate_aipw", "CI_left_aipw", "CI_right_aipw")]
out_aipw$method = "aipw"
colnames(out_aipw) <- col_names

out_lm <- outs[,c("const", "n", "iter", "estimate_lm", "CI_left_lm", "CI_right_lm")]
out_lm$method = "lm"
colnames(out_lm) <- col_names

 

 out_sieve_oracle <-out_sieveIF
 out_sieve_oracle$method <- "sieve_oracle"
 
 out_sieve_oracle[, CI_left:= estimate - qnorm(1-0.05/2) * sd(estimate), by = c("const", "n")]
 out_sieve_oracle[, CI_right:= estimate + qnorm(1-0.05/2) * sd(estimate), by = c("const", "n")]
 
 
 results <- rbind(out_sieve_oracle, out_sieveIF, out_sieveIF_df, out_sieveboot, out_tmle, out_aipw, out_lm)


coverage <- results[, mean(ATE >= CI_left & ATE <= CI_right, na.rm=T), by = c("const", "method", "n")]
CI_width <- results[, mean(CI_right - CI_left, na.rm=T), by = c("const", "method", "n")]
cov_oracle = results[, mean(abs(estimate-ATE) <=  1.959964 * sd(estimate))  ,  by = c("const", "n", "method")]
bias <- results[, mean(estimate - ATE), by = c("const", "method", "n")]
se <- results[, sd(estimate - ATE, na.rm=T), by = c("const", "method", "n")]

plot_data <- data.table(const = coverage$const, method = coverage$method, n = coverage$n,  cov_oracle=cov_oracle[[4]],
           bias = abs(bias[[4]]),
           se = se[[4]],
           coverage = coverage[[4]],
           CI_width = CI_width[[4]]
           )

library(ggplot2)
 
ggplot(plot_data[method %in% c("lm", "aipw", "tmle", "sieve_IF")], aes(x=n, y = bias, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical Bias", color = "Method", group = "Method", linetype = "Method")


 #ggsave("SimPlotLassoHighDim_bias.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_bias.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_bias.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsmallSample_bias.pdf", width = 7, height = 4)

ggplot(plot_data[method %in% c("lm", "aipw", "tmle", "sieve_IF")], aes(x=n, y = se, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical Standard Error", color = "Method", group = "Method", linetype = "Method")


#ggsave("SimPlotHALsmallSample_se.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_se.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_se.pdf", width = 7, height = 4)
# ggsave("SimPlotLassoHighDim_se.pdf", width = 7, height = 4)

 
 
 
ggplot(plot_data[method %in% c("aipw", "tmle","lm", "sieve_IF_df_adjusted")] , aes(x=n, y = cov_oracle, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Oracle CI coverage", color = "Method", group = "Method", linetype = "Method") + scale_y_continuous( )

#ggsave("SimPlotHALsmallSample_coverage_oracle.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_coverage_oracle.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_coverage_oracle.pdf", width = 7, height = 4)
 #ggsave("SimPlotLassoHighDim_coverage_oracle.pdf", width = 7, height = 4)


 plot_data <- plot_data[!(method %in% c("lm", "aipw", "tmle"))]
 
 
 
 
 ggplot(plot_data , aes(x=n, y = coverage, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical CI coverage", color = "Method", group = "Method", linetype = "Method") + scale_y_continuous(breaks = c(0.95,0.94, 0.93, 0.92, 0.91, 0.9, 0.8))

#ggsave("SimPlotHALsmallSample_coverage.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_coverage.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_coverage.pdf", width = 7, height = 4)
 #ggsave("SimPlotLassoHighDim_coverage.pdf", width = 7, height = 4)


ggplot(plot_data[!(method %in% c("aipw", "tmle"))] , aes(x=n, y = coverage, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))  + labs(x = "Sample Size (n)", y = "Empirical CI coverage", color = "Method", group = "Method", linetype = "Method")

ggplot(plot_data  , aes(x=n, y = CI_width, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5)) + labs(x = "Sample Size (n)", y = "Average CI width", color = "Method", group = "Method", linetype = "Method")


#ggsave("SimPlotHALsmallSample_CI_width.pdf", width = 7, height = 4)

 ggsave("SimPlotHALcomplex_CI_width.pdf", width = 7, height = 4)
#ggsave("SimPlotHALsimple_CI_width.pdf", width = 7, height = 4)
# ggsave("SimPlotLassoHighDim_CI_width.pdf", width = 7, height = 4)


ggplot(plot_data[!(method %in% c("aipw", "tmle"))] , aes(x=n, y = CI_width, group = method, color = method, linetype=method)) + geom_line() +  facet_wrap(~ const) + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5)) + labs(x = "Sample Size (n)", y = "Average CI width", color = "Method", group = "Method", linetype = "Method")

#ggsave("SimPlot.pdf", width = 8, height = 5)
```

```{r}
ATE = 1
print("sieve IF")
   
    print(outs[,mean(ATE >= CI_left & ATE <= CI_right), by = c("name", "const", "n")] )
     print(outs[, mean(as.numeric(CI_right) - as.numeric(CI_left)), by = c("name", "const", "n")])
     print("sieve IF - df adjusted")
        print(outs[,mean(ATE >= CI_df_left & ATE <= CI_df_right), by = c("name", "const", "n")] )
         print(outs[, mean(as.numeric(CI_df_right) - as.numeric(CI_df_left)), by = c("name", "const", "n")])
 print("sieve IF - boot")
    print(    outs[,mean(ATE >= CI_boot_left & ATE <= CI_boot_right), by = c("name", "const", "n")] )
   print(outs[, mean(as.numeric(CI_boot_right) - as.numeric(CI_boot_left)), by = c("name", "const", "n")])

 
    print("tmle")
    print(    outs[,mean(ATE >= CI_left_tmle & ATE <= CI_right_tmle), by = c("name", "const", "n")] 
)
     print(outs[, mean(as.numeric(CI_right_tmle) - as.numeric(CI_left_tmle)), by = c("name", "const", "n")])
     print("lm")
    print(    outs[,mean(ATE >= CI_left_lm & ATE <= CI_right_lm), by = c("name", "const", "n")] 
)
     print(outs[, mean(as.numeric(CI_right_lm) - as.numeric(CI_left_lm)), by = c("name", "const", "n")])
     
     
# 
```
 
```{r}
 
 library(data.table)
 

 run_sims <- function(const, n, nsims,  formula_hal = ~ h(.) + h(.,A), num_knots = c(1,1), screen_basis = F, gen_fun, lrnr_pi = Lrnr_glmnet$new(), lrnr_g = Lrnr_glmnet$new(formula = ~ . + A * .),nboots = 500) {
    
         out_list <- list()
  out <- lapply(1:nsims, function(iter) {
    try({
    print("Current settings:")
    print(n)
    print(const)
    print(iter)
             datam_list <- gen_fun(const)(n)

     X <- datam_list$X
    A <- datam_list$A
    Y <- datam_list$Y
    
    g_basis_gen <-make_g_basis_generator_HAL(X,A,Y, formula_hal =formula_hal, smoothness_orders=1, num_knots = num_knots, max_degree = 2, screen_basis = screen_basis)
    # datam_list_oracle <- gen_fun(const)(n=5000)
    # g_basis_oracle <- g_basis_gen(X=datam_list_oracle$X, A=datam_list_oracle$A)
    # print(dim(g_basis_oracle))
    # beta <- coef(glm.fit(g_basis_oracle, datam_list_oracle$Y, family = gaussian()))
    # ATE <- mean((g_basis_gen(X=datam_list_oracle$X, A= 1)-g_basis_gen(X=datam_list_oracle$X, A= 0) ) %*%beta)
    ATE <- datam_list$ATE
    
    causal_sieve <- causalsieve$new(X, A, Y, g_basis_gen, nboots = nboots)
    causal_sieve$add_target_parameter(g(A=1,X=X) - g(A=0,X=X) ~ 1, name = "ATE")
   # causal_sieve$add_target_parameter(g(A=1,X=X) - g(A=0,X=X) ~ 1 + W1)
    causal_sieve$estimate()
    #\causal_sieve$summary()
    name <- unlist(sapply(causal_sieve$estimates, `[[`, "name"))

    estimates <- unlist(sapply(causal_sieve$estimates, `[[`, "estimate"))
    CI_IF_df <- do.call(rbind, lapply(causal_sieve$estimates, `[[`, "CI"))
    causal_sieve$confint(include_se_df_correction = FALSE)
    CI_IF <- do.call(rbind, lapply(causal_sieve$estimates, `[[`, "CI"))
    CI_boot <- do.call(rbind, lapply(causal_sieve$estimates, `[[`, "CI_boot"))
    out <- cbind(t(as.data.table(c(iter, name))), t(as.data.table(as.numeric(c(estimates, CI_IF, CI_IF_df, CI_boot)))))
 print(t(as.data.table(as.numeric(c(estimates, CI_IF, CI_IF_df, CI_boot)))))
 
    colnames(out) <- c("iter", "name", "estimate", "CI_left", "CI_right", "CI_df_left", "CI_df_right", "CI_boot_left", "CI_boot_right")
    #
 
    data <- as.data.frame(cbind(X,A,Y))
    g_ests <- compute_g(data, lrnr_g = lrnr_g)
    g1 <- g_ests$g1
    g0 <- g_ests$g0
    pi <-compute_pi(as.data.frame(cbind(X,A,Y)), lrnr_pi = lrnr_pi)
    tmle <- compute_TMLE (data, pi, g1, g0,level = 0.05)
    aipw <- compute_AIPW (data, pi, g1, g0,level = 0.05)
    lm <- compute_glm (data,level = 0.05)
    
    comp <- as.numeric(unlist(c(tmle[-2], aipw[-2], lm[-2])))
    names(comp) <- c(paste0(c("estimate", "CI_left", "CI_right"), "_tmle"),
                     paste0(c("estimate", "CI_left", "CI_right"), "_aipw"),
                     paste0(c("estimate", "CI_left", "CI_right"), "_lm"))
    # 
    out <- cbind(out, t(as.data.table(comp)))
    colnames(out) <- c(
      c("iter", "name", "estimate", "CI_left", "CI_right", "CI_df_left", "CI_df_right", "CI_boot_left", "CI_boot_right"), 
       c(paste0(c("estimate", "CI_left", "CI_right"), "_tmle"),
                     paste0(c("estimate", "CI_left", "CI_right"), "_aipw"),
                     paste0(c("estimate", "CI_left", "CI_right"), "_lm"))
    )
    out_list[[iter]] <<- out
    out_full <- as.data.table(do.call(rbind, out_list))
   
   print("sieve IF")
   
    print(out_full[,mean(ATE >= CI_left & ATE <= CI_right), by = "name"][[2]])
     print(out_full[, mean(as.numeric(CI_right) - as.numeric(CI_left))])
     print("sieve IF - df adjusted")
        print(out_full[,mean(ATE >= CI_df_left & ATE <= CI_df_right), by = "name"][[2]])
         print(out_full[, mean(as.numeric(CI_df_right) - as.numeric(CI_df_left))])
 print("sieve IF - boot")
    print(    out_full[,mean(ATE >= CI_boot_left & ATE <= CI_boot_right), by = "name"][[2]])
   print(out_full[, mean(as.numeric(CI_boot_right) - as.numeric(CI_boot_left))])

 
    print("tmle")
    print(    out_full[,mean(ATE >= CI_left_tmle & ATE <= CI_right_tmle), by = "name"][[2]]
)
     print(out_full[, mean(as.numeric(CI_right_tmle) - as.numeric(CI_left_tmle))])
     print("lm")
    print(    out_full[,mean(ATE >= CI_left_lm & ATE <= CI_right_lm), by = "name"][[2]]
)
     print(out_full[, mean(as.numeric(CI_right_lm) - as.numeric(CI_left_lm))])
    
    return(out)
    })
  })
  
  out <- as.data.frame(do.call(rbind, out_list))
  out$const <- const
  out$n <- n
  return(out)
  
} 

```
