---
title: "simsWager"
output: html_document
date: '2022-12-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(data.table)
library(ggplot2)
type <- "beta"
ns <- c(500, 1000, 1500, 2000, 3000)
out <- rbindlist(lapply(ns, function(n){
  data <- fread(paste0("simScripts/simsWager_", type, "_", n, "d2k2_new.csv" ))
  bias <- mean(data$estimate - data$trueATE)
  se <- sd(data$estimate)
  cover <- mean(data$cover_true)
  bias_DR <- mean(data$DR_estimate - data$trueATE)
  se_DR <- sd(data$DR_estimate)
  cover_DR <- mean(data$DR_cover_true)
  data.frame(type = type, n = n, method = c("AdaLSE", "DR"), "se" = c(se, se_DR), "bias" = c(bias, bias_DR), "coverage" = c(cover, cover_DR))
}))


ggplot(out, aes(x = n, y = coverage, color = method)) + geom_line()
ggplot(out, aes(x = n, y = bias, color = method)) + geom_line()
ggplot(out, aes(x = n, y = se, color = method)) + geom_line()

```

```{r}
doMC::registerDoMC(cores = 11)
library(hal9001)
library(glmnet)
nsims <- 100
n <- 500

sim_generator <- sim_scaledNorm
ns <- c(500, 1000, 1500, 2000)
d <- 3
k <- 2
results <- run_sims(n, d, k, sim_generator, nsims) 

sim_generator <- sim_beta
ns <- c(500, 1000, 1500, 2000)
d <- 5
k <- 3
results <- run_sims(n, d, k, sim_generator, nsims) 

sim_generator <- sim_Pois
ns <- c(500, 1000, 1500, 2000)
d <- 5
k <- 3
results <- run_sims(n, d, k, sim_generator, nsims) 


sim_generator <- sim_logNorm
ns <- c(500, 1000, 1500, 2000)
d <- 5
k <- 3
results <- run_sims(n, d, k, sim_generator, nsims) 

```



```{r}
# alpha  = theta^2
#  beta = theta
# gives mean theta and variance 1.
 
d <- 3
k <- 2
multiplier <-1
sim_beta <- function(n, d, k) {
  pi <- 3.14
  X <- as.matrix(replicate(d, runif(n, -1 , 1)))
  colnames(X) <- paste0("X", 1:ncol(X))
  zeta <- rowSums(X[,1:k, drop = F]) / sqrt(k)
  eta <- sign(zeta) * zeta^2
  alpha <- pmax(0.05, pmin(0.95, 1 / (1+ exp(- eta))))
  W <- rbeta(n, alpha, 1 - alpha)
  mu <- eta + 0.2* (alpha - 0.5)
  tau <- -0.2
  theta <- mu + W * multiplier*tau  + 3
  if(any(theta <0 )) {
    print(range(theta))
    warning("Theta has negative values")
  }
  Y <- rgamma(n, shape = theta^2, rate = abs(theta))
  tau <-  abs(mu + 1 * multiplier*tau  + 3) -   abs(mu + 0 * multiplier*tau  + 3) 
   return(as.data.frame(cbind(X,W,Y, theta = theta, tau = tau, ATE = mean(tau))))
}

sim_Pois <- function(n, d, k) {
   pi <- 3.14
  X <- as.matrix(replicate(d, runif(n, -1 , 1)))
  colnames(X) <- paste0("X", 1:ncol(X))
  tau <- rowMeans(cos(X[, 1:k, drop = F]*pi /3))
  lambda <- 0.2 + tau^2
  mu <- 4 * rowMeans(X) + 2* lambda
  W <- rpois(n, lambda)
  theta <- mu + W * multiplier*tau + 4
  if(any(theta <0 )) {
    warning("Theta has negative values")
  }
  Y <- rgamma(n, shape = theta^2, rate = abs(theta))
  tau <-  abs(mu + 1 * multiplier*tau  + 4) -   abs(mu + 0 * multiplier*tau  + 4) 
   return(as.data.frame(cbind(X,W,Y, theta = theta, tau = tau, ATE = mean(tau))))
}

sim_scaledNorm <- function(n, d, k) {
   pi <- 3.14
  X <- as.matrix(replicate(d, runif(n, -1 , 1)))
  colnames(X) <- paste0("X", 1:ncol(X))
  eta <- sign(X[, 1:k, drop = F]) * sqrt(abs(X[, 1:k, drop = F]))
  mu <-2^(k-1) * apply(eta, 1 , prod)
  #mu <-   sign(eta) * sqrt(abs(eta))
  lambda <- 0.1 * sign(mu) + mu
  tau <- (pmax(X[,1],0) + pmax(X[,2], 0)) / 2
  W <- rnorm(n, mean = lambda, sd = abs(lambda))
  theta <- mu + W * multiplier*tau + 10
  if(any(theta <0 )) {
    warning("Theta has negative values")
  }
   Y <- rgamma(n, shape = theta^2, rate = abs(theta))
  tau <-  abs(mu + 1 * multiplier*tau  + 10) -   abs(mu + 0 * multiplier*tau  + 10) 
   return(as.data.frame(cbind(X,W,Y, theta = theta, tau = tau, ATE = mean(tau))))
}

sim_logNorm <- function(n, d, k) {
   pi <- 3.14
   X <- as.matrix(replicate(d, runif(n, -1 , 1)))
  colnames(X) <- paste0("X", 1:ncol(X))
  zeta <- rowSums(X[,1:k, drop = F]) / sqrt(k)
  mu <- pmax(0, 2*zeta)
  lambda <- 1 / (1 + exp(-sign(zeta) * zeta^2))
  tau <- sin(2 * pi * X[,1])
  W <- exp(rnorm(n, mean = lambda, sd = 1/3))
  theta <- mu + W * multiplier*tau  + 6
  if(any(theta <0 )) {
    warning("Theta has negative values")
  }
   Y <- rgamma(n, shape = theta^2, rate = abs(theta))
  tau <-  abs(mu + 1 * multiplier*tau  + 6) -   abs(mu + 0 * multiplier*tau  + 6) 
   return(as.data.frame(cbind(X,W,Y, theta = theta, tau = tau, ATE = mean(tau))))
}

mean(sim_beta(n,d,k)$ATE)
mean(sim_Pois(n,d,k)$ATE)
mean(sim_scaledNorm(n,d,k)$ATE)
mean(sim_logNorm(n,d,k)$ATE)
```


```{r}


get_projection <- function(sim_generator, d, k) {
data_big <- sim_generator(n= 50000,d,k)
X <- as.matrix(data_big[,paste0("X", 1:k)])
A <- data_big$W
Y <-  data_big$Y
theta <- data_big$theta

basis_list_mu <- hal9001::enumerate_basis((X), max_degree = 1, num_knots = c(100,1, 1 ), smoothness_orders =1)
basis_list_tau <- hal9001::enumerate_basis((X), max_degree = 1, num_knots = c(100,1), smoothness_orders = 1)
x_basis_mu <- cbind(1, as.matrix(make_design_matrix(X, basis_list_mu, 0.9))) 
x_basis_tau <- cbind(1, as.matrix(make_design_matrix(X, basis_list_tau, 0.9))) 
x_basis <- cbind(  x_basis_mu, A * x_basis_tau)
penalty.factor <-  rep(1, ncol(x_basis))
#lasso_fit <- glmnet::glmnet(x_basis, theta, family = "gaussian", lambda = 1e-10,  intercept = F,   standardize = FALSE)
#beta <- as.vector(coef(lasso_fit, s = "lambda.min"))[-1]
 
lasso_fit <- speedglm::speedlm.fit(theta,x_basis,  intercept = F )
beta <- coef(lasso_fit)
beta[is.na(beta)] <- 0
x_basis_lasso_A1 <- cbind(x_basis_mu, 1 * x_basis_tau)  
x_basis_lasso_A0 <- cbind(x_basis_mu, 0 * x_basis_tau) 
 
ATE_approx <- mean((x_basis_lasso_A1 - x_basis_lasso_A0) %*% beta)
ATE_approx
}

 
```

```{r}
doMC::registerDoMC(cores = 11)
library(hal9001)
library(glmnet)
sim_generator <- sim_scaledNorm
n <- 1500
d <- 5
k <- 3
nsims <- 20
results <- run_sims(n, d, k, sim_generator, nsims) 


```



```{r}
#data_big <- sim_generator(n= 500000,d,k)
run_sims <- function(n, d, k, sim_generator) {
trueATE <- get_projection(sim_generator, d, k)
for(iter in 1:nsims) {
  try({
data <- sim_generator(n,d,k)
X <- as.matrix(data[,paste0("X", 1:d)])
A <- data$W
Y <- data$Y
 
print(trueATE)
#fit_hal_g_params <- list(formula <- ~ h(.) + h(.,A), max_degree = 2, num_knots = c(20,20), smoothness_orders = 1)
basis_list_mu <- hal9001::enumerate_basis((X), max_degree = 1, num_knots = c(100,20, 1 ), smoothness_orders =1)
basis_list_tau <- hal9001::enumerate_basis((X), max_degree = 1, num_knots = c(100, 1), smoothness_orders = 1)

x_basis_mu <- cbind(1, as.matrix(make_design_matrix(X, basis_list_mu, 0.9))) 
x_basis_tau <- cbind(1, as.matrix(make_design_matrix(X, basis_list_tau, 0.9))) 

# add intercept
x_basis <- cbind(  x_basis_mu, A * x_basis_tau)
penalty.factor <-  rep(1, ncol(x_basis))
#penalty.factor[1] <- 0
#penalty.factor[1 + ncol(x_basis_mu)] <- 0

# Compute lasso fit
lasso_fit <- glmnet::cv.glmnet(x_basis, Y, family = "gaussian", intercept = F, penalty.factor = penalty.factor, relax = F, gamma = 0, parallel = T, standardize = FALSE)
beta <- as.vector(coef(lasso_fit, s = "lambda.min"))[-1]
keep_cols_1 <- which(abs(beta) > 1e-3)
x_basis_lasso <- x_basis[, keep_cols_1, drop = F]
print(dim(x_basis_lasso))
print( mean(cbind(  x_basis_mu, 1 * x_basis_tau)  %*% beta -  cbind(  x_basis_mu, 0 * x_basis_tau)  %*% beta)
 )

# Compute relaxed fit
#relaxed_fit <- glmnet::cv.glmnet( x_basis_lasso, Y, family = "gaussian" ,intercept = F) # screen hyper correlates variables just in case
relaxed_fit <- glm.fit( x_basis_lasso, Y, family = gaussian() ,intercept = F) 
beta_relaxed <- coef(relaxed_fit)#[-1]
keep_cols_2 <-  which(!is.na(beta_relaxed) & abs(beta_relaxed) > 1e-3 )
x_basis_lasso <- x_basis_lasso[,keep_cols_2, drop = F]
x_basis_lasso_A1 <- cbind(x_basis_mu, 1 * x_basis_tau)[, keep_cols_1, drop = F][, keep_cols_2, drop = F] 
x_basis_lasso_A0 <- cbind(x_basis_mu, 0 * x_basis_tau)[, keep_cols_1, drop = F][, keep_cols_2, drop = F] 
relaxed_fit <- glm.fit(x_basis_lasso, Y, family = gaussian(), intercept = F) # redo fit with uncorrelated variables
beta <- coef(relaxed_fit) # get final beta estimate for AdaLSE

solve(t(x_basis_lasso)  %*% x_basis_lasso / n, t(x_basis_lasso) %*% Y)
# Compute empirical Riesz representor
theta_n_basis_row <- colMeans(x_basis_lasso_A1 - x_basis_lasso_A0)
alpha <- x_basis_lasso %*% solve(t(x_basis_lasso)  %*% x_basis_lasso / n, theta_n_basis_row)

IF <-  alpha * (Y - as.vector(x_basis_lasso %*% beta)) + as.vector(theta_n_basis_row %*% beta) - mean(theta_n_basis_row %*% beta)
se <- sd(IF)/sqrt(n) * sqrt(n) / sqrt(n - ncol(x_basis_lasso))
# Compute estimate of ATE
est <- mean(theta_n_basis_row %*% beta)
CI <- est + c(-1, 1) * abs(qnorm(1-0.975)) * se
cover <- as.numeric(trueATE >= CI[1] & trueATE <= CI[2])
sim_list$estimate <- c(sim_list$estimate , est)
sim_list$CI <- c(sim_list$CI , CI)
sim_list$cover <- c(sim_list$cover , cover)
sim_list$se <- c(sim_list$se, se)
print(est)
print(se)
print(cover)
print(mean(sim_list$cover ))
print(table(sim_list$cover ))

}) # end try
  
}
return(sim_list)

}
 
 
```










